In [1]:
import tensorflow as tf 

In [2]:
tf.__version__

'2.3.0'

In [3]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [5]:
for ele in dataset:
    print(ele)
    print(ele.numpy())

tf.Tensor(1, shape=(), dtype=int32)
1
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor(4, shape=(), dtype=int32)
4
tf.Tensor(5, shape=(), dtype=int32)
5
tf.Tensor(6, shape=(), dtype=int32)
6
tf.Tensor(7, shape=(), dtype=int32)
7


In [6]:
dataset = tf.data.Dataset.from_tensor_slices([[1, 2], [3, 4], [5, 6]])

In [7]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [8]:
for ele in dataset:
    print(ele)
    print(ele.numpy())

tf.Tensor([1 2], shape=(2,), dtype=int32)
[1 2]
tf.Tensor([3 4], shape=(2,), dtype=int32)
[3 4]
tf.Tensor([5 6], shape=(2,), dtype=int32)
[5 6]


In [9]:
dataset_dic = tf.data.Dataset.from_tensor_slices({'a':[1,2,3,4],
                                                 'b':[6,7,8,9],
                                                 'c':[12,13,14,15]})

In [10]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [11]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}
