In [1]:
import tensorflow as tf 
import numpy as np 

In [2]:
tf.__version__

'2.3.0'

In [3]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [4]:
dataset.take(4)

<TakeDataset shapes: (), types: tf.int32>

In [5]:
for ele in dataset.take(4):
    print(ele)
    print(ele.numpy())

tf.Tensor(1, shape=(), dtype=int32)
1
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor(4, shape=(), dtype=int32)
4


In [6]:
# dataset 是一个 iterable 的
iter_dataset = iter(dataset.take(4))

In [7]:
next(iter_dataset)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
next(iter_dataset)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
# dataset 进行洗牌（乱序）
dataset_shuffle = dataset.shuffle(7)

In [10]:
for ele in dataset_shuffle:
    print(ele.numpy())

7
4
3
5
2
1
6


In [11]:
# dataset 循环出现 count 次
dataset_repeat = dataset_shuffle.repeat(count=3)

In [12]:
for ele in dataset_repeat:
    print(ele.numpy())

2
7
5
4
3
6
1
1
4
7
2
3
6
5
3
7
2
1
5
6
4


In [13]:
# 指定 dataset 没出释放的 batch 的大小
dataset_batch = dataset_repeat.batch(3)

In [14]:
for ele in dataset_batch:
    print(ele.numpy())

[5 2 7]
[1 4 3]
[6 7 4]
[1 3 6]
[5 2 4]
[2 7 5]
[6 3 1]


In [15]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6, 7]))

In [16]:
# 在 dataset 上应用函数
dataset_map = dataset.map(tf.square)

In [17]:
for ele in dataset_map:
    print(ele.numpy())

1
4
9
16
25
36
49
