In [1]:
import tensorflow as tf 

In [2]:
tf.__version__

'2.3.0'

In [3]:
v = tf.Variable(0.0)

In [4]:
v + 1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [5]:
(v + 1).numpy()

1.0

In [6]:
v.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=5.0>

In [7]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [8]:
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=6.0>

In [9]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=6.0>

In [10]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [11]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss = w * w

In [12]:
grad = tape.gradient(loss, w)

In [13]:
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [14]:
c = tf.constant(3.0)
with tf.GradientTape() as t:
    t.watch(c)
    c_loss = c * c

In [15]:
c_grad = t.gradient(c_loss, c)

In [16]:
c_grad

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>