In [1]:
import tensorflow as tf 

In [2]:
tf.__version__

'2.3.0'

# 对一个网络进行自定义的训练

In [3]:
(train_images, train_labels), _ = tf.keras.datasets.mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
train_images = tf.expand_dims(train_images, -1)

In [7]:
train_images.shape

TensorShape([60000, 28, 28, 1])

In [8]:
train_images = tf.cast(train_images/255, tf.float32)

In [9]:
train_labels = tf.cast(train_labels, tf.int64)

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))

In [11]:
dataset

<TensorSliceDataset shapes: ((28, 28, 1), ()), types: (tf.float32, tf.int64)>

In [12]:
dataset = dataset.shuffle(10000).batch(32)

In [13]:
dataset

<BatchDataset shapes: ((None, 28, 28, 1), (None,)), types: (tf.float32, tf.int64)>

In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, [3, 3], activation='relu', input_shape=(None, None, 1)),
    tf.keras.layers.Conv2D(32, [3, 3], activation='relu'),
    tf.keras.layers.GlobalMaxPooling2D(),
    tf.keras.layers.Dense(10)
])

In [15]:
optimizer = tf.keras.optimizers.Adam()

In [16]:
loss_func = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [17]:
features, labels = next(iter(dataset))

In [18]:
features.shape

TensorShape([32, 28, 28, 1])

In [19]:
labels.shape

TensorShape([32])

In [20]:
predictions = model(features)

In [21]:
predictions.shape

TensorShape([32, 10])

In [22]:
tf.argmax(predictions, axis=1)

<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8], dtype=int64)>

In [23]:
labels

<tf.Tensor: shape=(32,), dtype=int64, numpy=
array([5, 9, 1, 7, 7, 3, 9, 6, 4, 3, 8, 9, 2, 7, 7, 5, 5, 7, 6, 0, 2, 2,
       2, 4, 7, 0, 3, 4, 8, 7, 7, 6], dtype=int64)>

In [24]:
def cal_loss(model, x, y):
    y_ = model(x)
    return loss_func(y, y_)

In [25]:
def train_step(model, optimizer, images, labels):
    with tf.GradientTape() as tape:
        loss_step = cal_loss(model, images, labels)
    grads = tape.gradient(loss_step, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

In [26]:
def train(epochs, model, optimizer, dataset):
    for epoch in range(epochs):
        for (batch_index, (images, labels)) in enumerate(dataset):
            train_step(model, optimizer, images, labels)
        print('Epoch{} is finshed'.format(epoch))

In [27]:
# train(10, model, optimizer, dataset)

# tf.metrics 模块的使用

In [28]:
m = tf.keras.metrics.Mean('acc')

In [29]:
m(10)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [30]:
m(20)

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>

In [31]:
m.result().numpy()

15.0

In [32]:
m([30, 40])

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [33]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [34]:
m.reset_states()

In [35]:
m(1)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [36]:
m(2)

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [37]:
a = tf.keras.metrics.SparseCategoricalAccuracy('acc')

In [38]:
a(labels, model(features))

<tf.Tensor: shape=(), dtype=float32, numpy=0.0625>

In [39]:
acc = 0
for i, j in zip(tf.argmax(predictions, axis=1), labels):
    if i==j:
       acc +=1
acc/(predictions.shape[0])

0.0625